const EXERCISE_CATALOG = {
  'Cuádriceps': [
    { id:'SQ',  name:'Sentadilla libre (barra)',
      sets:4, reps:'6–10', rpe:'7–8', rest:'2–3 min',
      note:'Coloca la barra sobre los trapecios, pies a la anchura de hombros con ligera apertura hacia afuera. Baja manteniendo el pecho alto y las rodillas alineadas con los pies; descend hasta que los muslos queden paralelos al suelo o por debajo. Sube empujando el suelo, sin que las rodillas colapsen hacia adentro.' },
    { id:'LP',  name:'Prensa de piernas',
      sets:4, reps:'8–12', rpe:'7–8', rest:'2–3 min',
      note:'Coloca los pies en la parte alta de la plataforma, separados a la anchura de cadera. Baja el peso hasta que las rodillas formen ~90° sin que la zona lumbar se despegue del respaldo. Empuja con los talones al subir y no bloquees las rodillas arriba del todo.' },
    { id:'HS',  name:'Hack squat en máquina',
      sets:4, reps:'8–12', rpe:'7–8', rest:'2–3 min',
      note:'Apoya toda la espalda y los hombros contra el respaldo. Pies centrados en la plataforma a anchura de caderas. Baja de forma controlada hasta los 90° de rodilla manteniendo los talones apoyados; sube sin bloquear. Evita que las rodillas apunten hacia adentro en ningún momento.' },
    { id:'SS',  name:'Sentadilla en máquina Smith',
      sets:4, reps:'8–12', rpe:'7–8', rest:'2–3 min',
      note:'Adelanta los pies unos 15-20 cm respecto a la barra para reducir la carga en la rodilla. Mantén la espalda neutra y el pecho alto durante todo el movimiento. Baja de forma lenta y controlada; la guía de la barra compensa el equilibrio pero no te apoyes en ella para levantarte.' },
    { id:'QE',  name:'Extensión de cuádriceps',
      sets:3, reps:'10–15', rpe:'8', rest:'90 seg',
      note:'Ajusta el rodillo justo encima del tobillo y el respaldo para que la articulación de la rodilla quede alineada con el eje de la máquina. Extiende lentamente durante 2 seg y baja en 3 seg buscando el estiramiento máximo. Evita usar impulso; el movimiento debe ser limpio y controlado en todo el rango.' },
    { id:'SB',  name:'Sentadilla búlgara',
      sets:3, reps:'8–12', rpe:'8', rest:'2 min',
      note:'Apoya el empeine del pie trasero en un banco a la altura de la rodilla. El pie delantero debe estar lo suficientemente adelantado para que al bajar la rodilla no sobrepase el pie. Desciende en vertical manteniendo el torso ligeramente inclinado hacia adelante; sube empujando con el talón del pie delantero.' },
    { id:'PSQ', name:'Sentadilla pendular (máquina)',
      sets:4, reps:'8–12', rpe:'7–8', rest:'2–3 min',
      note:'Colócate en la plataforma con los pies a la anchura de caderas y los hombros bajo los apoyos. La trayectoria en arco de la máquina guía el movimiento: baja de forma controlada hasta que los muslos queden paralelos o por debajo, manteniendo el torso erguido. Sube empujando con los talones sin bloquear las rodillas arriba. Al no haber carga axial en la columna, puedes centrarte en la profundidad y la conexión muscular con el cuádriceps y el glúteo.' },
    { id:'ZA',  name:'Zancada con mancuernas',
      sets:3, reps:'10–12 por lado', rpe:'7', rest:'90 seg',
      note:'Da un paso amplio hacia adelante y baja la cadera en vertical hasta que la rodilla trasera casi toque el suelo. El torso permanece erguido y la rodilla delantera no debe sobrepasar la punta del pie. Empuja con el talón delantero para volver a la posición inicial con control.' },
  ],
  'Isquiotibiales': [
    { id:'RDL', name:'Romanian deadlift con mancuernas',
      sets:4, reps:'8–12', rpe:'7–8', rest:'2 min',
      note:'Desde de pie con las mancuernas delante de los muslos, bisagra desde la cadera —no desde la cintura— manteniendo la espalda recta y las mancuernas pegadas a las piernas. Baja hasta sentir tensión en los isquiotibiales (generalmente a media tibia) y sube apretando glúteos al final. Rodillas ligeramente flexionadas durante todo el movimiento.' },
    { id:'PMR', name:'Peso muerto rumano (con mancuernas o barra)',
      sets:4, reps:'8–10', rpe:'8.5', rest:'2 min',
      note:'Sustituimos la máquina rara por este clásico. Es el rey indiscutible del tamaño para el femoral y el glúteo en estiramiento. Controla la bajada y empuja la cadera hacia atrás.' },
    { id:'LC',  name:'Curl femoral tumbado',
      sets:3, reps:'10–15', rpe:'8', rest:'90 seg',
      note:'Tumbado boca abajo, ajusta el rodillo para que quede justo encima del talón. Flexiona las rodillas llevando los talones hacia los glúteos en 2 seg y baja en 3-4 seg controlando la fase excéntrica. Mantén la cadera pegada al banco; si se levanta, estás usando demasiado peso.' },
    { id:'CS',  name:'Curl femoral sentado',
      sets:3, reps:'10–15', rpe:'8', rest:'90 seg',
      note:'La posición sentada estira el bíceps femoral desde su origen proximal, aumentando la tensión en el estiramiento. Ajusta el respaldo para que el muslo quede bien apoyado y el rodillo en el tendón de Aquiles. Baja con control total en la fase excéntrica; es donde más se desarrolla el músculo.' },
    { id:'PM',  name:'Peso muerto en máquina (hack squat inv.)',
      sets:4, reps:'10–12', rpe:'7–8', rest:'2 min',
      note:'Colócate de espaldas a la máquina de hack squat, con los hombros bajo los rodillos. Ejecuta una bisagra de cadera pura: empuja las caderas hacia atrás mientras el torso baja, manteniendo la espalda neutral. Sin carga axial sobre la columna, es una opción segura para trabajar el patrón de peso muerto.' },
    { id:'NC',  name:'Nordic curl',
      sets:3, reps:'4–8', rpe:'8–9', rest:'2 min',
      note:'Arrodíllate con los pies sujetos. Desde posición erguida, baja el cuerpo hacia el suelo de forma absolutamente controlada contrayendo los isquiotibiales para resistir la caída —es un ejercicio excéntrico puro. Usa las manos para amortiguar al final y empuja para volver. Es exigente: empieza con pocas repeticiones.' },
  ],
  'Glúteos': [
    { id:'HT',  name:'Hip thrust con barra',
      sets:4, reps:'8–12', rpe:'7–8', rest:'2 min',
      note:'Apoya la zona media de la espalda en un banco, barra sobre las caderas (usa un pad). Pies a la anchura de cadera con rodillas a 90° en la posición alta. Empuja con los talones, eleva las caderas hasta que el torso quede horizontal y aprieta los glúteos arriba. Baja sin tocar el suelo entre repeticiones.' },
    { id:'HTM', name:'Hip thrust en máquina',
      sets:4, reps:'10–15', rpe:'7–8', rest:'90 seg',
      note:'Ajusta el rodillo para que quede sobre las caderas, no sobre el abdomen. Empuja con los talones en la extensión completa y mantén la contracción 1 segundo arriba. La máquina guía el movimiento pero asegúrate de no hiperlordosar la lumbar al llegar arriba.' },
    { id:'PT',  name:'Patada trasera en polea baja',
      sets:3, reps:'12–15 por lado', rpe:'7', rest:'60 seg',
      note:'Coloca la tobillera en el pie de trabajo y apóyate en el soporte. Mantén la cadera estable y el core activado; el movimiento solo ocurre en la articulación de la cadera. Extiende la pierna hacia atrás sin arquear la lumbar ni rotar la cadera. Regresa lentamente resistiendo la carga.' },
    { id:'ABM', name:'Abducción en máquina',
      sets:3, reps:'15–20', rpe:'7', rest:'60 seg',
      note:'Siéntate erguido con la espalda pegada al respaldo. Abre las rodillas hacia afuera de forma controlada hasta el rango máximo cómodo y regresa lentamente sin dejar que los pesos choquen. Evita inclinar el torso hacia los lados como compensación; el movimiento es puro de cadera.' },
  ],
  'Pantorrillas': [
    { id:'CA',  name:'Elevación de talones de pie',
      sets:4, reps:'12–20', rpe:'7', rest:'60 seg',
      note:'Coloca la punta del pie en un escalón para obtener rango completo. Baja el talón hasta sentir estiramiento en el gemelo y sube hasta la máxima contracción, haciendo pausa de 1 seg arriba. El gemelo trabaja mejor con la rodilla extendida. Usa un peso que permita rango completo, no carga excesiva con medio rango.' },
    { id:'TS',  name:'Elevación de talones sentado',
      sets:4, reps:'15–20', rpe:'7', rest:'60 seg',
      note:'Con la rodilla flexionada a 90° se aísla el sóleo, que es el músculo más profundo de la pantorrilla. Coloca las rodillas bajo los rodillos y busca rango completo: estiramiento abajo, pausa y contracción total arriba. Al estar sentado el gemelo está relajado, así que el sóleo recibe toda la carga.' },
    { id:'DC',  name:'Donkey calf raise',
      sets:3, reps:'12–15', rpe:'7', rest:'60 seg',
      note:'Con la cadera flexionada a ~90° y el torso inclinado, los gemelos trabajan en su posición de mayor estiramiento. Apoya la punta del pie en una superficie elevada y realiza el movimiento completo: talón abajo, pausa, y sube hasta máxima contracción. Este ángulo de cadera aumenta la activación del gemelo respecto a la variante de pie.' },
  ],
  'Pecho': [
    { id:'PBB', name:'Press banca plana con barra',
      sets:4, reps:'6–10', rpe:'7–8', rest:'2–3 min',
      note:'Agarre algo más ancho que los hombros, baja la barra al esternón medio manteniendo los codos a unos 45-60° del torso. Crea un arco natural en la espalda con los omóplatos retraídos y los pies apoyados en el suelo. Sube en trayectoria ligeramente diagonal hacia los hombros, no en vertical.' },
    { id:'PBM', name:'Press banca plana con mancuernas',
      sets:4, reps:'8–12', rpe:'7–8', rest:'2–3 min',
      note:'Las mancuernas permiten mayor rango de movimiento que la barra. Baja con los codos a unos 75° respecto al torso y lleva las mancuernas hasta que los codos queden ligeramente por debajo del banco. Sube describiendo un arco suave sin que las mancuernas choquen arriba; mantén la tensión en el pecho durante toda la serie.' },
    { id:'PI',  name:'Press inclinado con mancuernas',
      sets:4, reps:'8–12', rpe:'7–8', rest:'2–3 min',
      note:'Banco a 30-45°, ángulos mayores convierten el ejercicio en trabajo de hombros. Baja las mancuernas con control manteniendo los codos a ~60° del torso. El pecho superior tarda en responder: trabaja con constancia, contracción consciente y rango completo en lugar de añadir peso precipitadamente.' },
    { id:'PD',  name:'Press declinado con mancuernas',
      sets:3, reps:'10–12', rpe:'7–8', rest:'90 seg',
      note:'El banco a -15-30° dirige la carga hacia el pecho inferior y esternal. Mantén los omóplatos retraídos y el core apretado para estabilizarte en la posición declinada. El movimiento es el mismo que el press plano; baja hasta sentir estiramiento en el pecho y sube describiendo un arco.' },
    { id:'AP',  name:'Apertura en polea media',
      sets:3, reps:'12–15', rpe:'8', rest:'90 seg',
      note:'Con los cables desde abajo, el vector de fuerza se dirige hacia arriba y al centro, lo que maximiza la tensión en la parte superior del pecho. Mantén una ligera flexión en los codos durante todo el movimiento. Controla la apertura para que el pecho siempre esté bajo tensión y aprieta en el punto de cruce.' },
    { id:'AMP', name:'Aperturas con mancuernas planas',
      sets:3, reps:'12–15', rpe:'8', rest:'90 seg',
      note:'Tumbado en banco plano, baja las mancuernas con los codos ligeramente doblados describiendo un arco amplio hasta sentir estiramiento profundo en el pecho. Sube por la misma trayectoria apretando el pecho como si quisieras juntar las manos. No es un ejercicio de fuerza; prioriza la amplitud de movimiento y la conexión muscular.' },
    { id:'FO',  name:'Fondos en máquina o banco',
      sets:3, reps:'10–15', rpe:'7', rest:'90 seg',
      note:'Para enfatizar el pecho, inclina el torso ligeramente hacia adelante y abre los codos hacia afuera. Baja hasta sentir estiramiento en el pecho sin llegar al punto de incomodidad en el hombro. Los fondos en paralelas con torso vertical activan más el tríceps; la inclinación es la clave para redirigir la carga al pecho.' },
    { id:'PO',  name:'Pullover en polea o mancuerna',
      sets:3, reps:'12–15', rpe:'7', rest:'90 seg',
      note:'Tumbado en banco perpendicular, mantén los codos ligeramente flexionados y fijos durante todo el movimiento. Baja la mancuerna/polea describiendo un arco sobre la cabeza hasta sentir estiramiento en dorsal y pecho; sube llevando el peso sobre el pecho. Activa tanto dorsal como pecho inferior.' },
  ],
  'Espalda': [
    { id:'JP',  name:'Jalón al pecho en polea',
      sets:4, reps:'8–12', rpe:'7–8', rest:'2 min',
      note:'Agarre algo más ancho que los hombros, pecho alto y ligera inclinación del torso hacia atrás. Inicia el tirón bajando las escápulas antes de doblar los codos —así el dorsal trabaja desde el inicio. Lleva la barra al esternón y baja de forma controlada para estirar completamente el dorsal en cada repetición.' },
    { id:'JN',  name:'Jalón con agarre neutro cerrado',
      sets:3, reps:'10–15', rpe:'7', rest:'90 seg',
      note:'El agarre neutro y estrecho permite un rango de movimiento mayor y reduce la tensión en el manguito rotador. Siéntate erguido, saca el pecho y lleva el mango hacia el esternón activando los codos hacia las costillas. Controla la subida estirando el dorsal completamente antes de la siguiente repetición.' },
    { id:'DOM', name:'Dominadas (peso corporal)',
      sets:4, reps:'5–10', rpe:'8–9', rest:'2–3 min',
      note:'Cuelga con los brazos completamente extendidos y activa las escápulas antes de tirar —esto protege el hombro. Sube llevando el pecho a la barra y los codos hacia las caderas, no hacia atrás. Baja de forma lenta y controlada (3-4 seg) para maximizar el trabajo excéntrico del dorsal.' },
    { id:'RP',  name:'Remo en polea baja',
      sets:4, reps:'10–12', rpe:'7–8', rest:'2 min',
      note:'Siéntate erguido con las rodillas ligeramente flexionadas. Tira del mango hacia el abdomen bajo manteniendo los codos pegados al cuerpo y apretando los omóplatos al final del movimiento. Evita balancear el torso hacia atrás para meter más peso; el movimiento debe ser de brazos y espalda, no de inercia.' },
    { id:'RB',  name:'Remo con barra',
      sets:4, reps:'8–10', rpe:'7–8', rest:'2 min',
      note:'Inclina el torso a 45° con la espalda neutra y tira de la barra hacia el ombligo, no hacia el pecho. Los codos pasan cerca del cuerpo y los omóplatos se retraen al final. Mantén el core muy activado para proteger la lumbar; el peso debe ser el que permita hacer el movimiento limpio, no el máximo que puedas arrancar.' },
    { id:'RM',  name:'Remo con mancuerna',
      sets:3, reps:'10–12 por lado', rpe:'7–8', rest:'90 seg',
      note:'Apoya la rodilla y la mano del mismo lado en el banco para estabilizarte. Tira de la mancuerna hacia la cadera —no hacia el hombro— con el codo bien pegado al cuerpo. Rota ligeramente el torso al final para obtener mayor contracción del dorsal. Estira completamente el brazo en la fase de bajada.' },
    { id:'PPO', name:'Pull-over en polea alta',
      sets:3, reps:'12–15', rpe:'7', rest:'90 seg',
      note:'De pie frente a la polea alta, toma la barra con los brazos extendidos. Manteniendo los codos fijos y casi rectos, tira hacia abajo describiendo un arco hasta que las manos lleguen a los muslos. El movimiento es puro de hombro, no de codo. Controla el retorno para que el dorsal trabaje también en excéntrico.' },
  ],
  'Hombros': [
    { id:'PH',  name:'Press de hombros con mancuernas',
      sets:4, reps:'8–12', rpe:'7–8', rest:'2 min',
      note:'Siéntate en banco con respaldo vertical. Sube las mancuernas desde la altura de las orejas hasta casi la extensión completa sin bloquear el codo. Evita arquear la zona lumbar; si necesitas arquear para llegar arriba, baja el peso. Los codos deben describir un ángulo de unos 90° en la posición baja.' },
    { id:'PMB', name:'Press militar con barra',
      sets:4, reps:'6–10', rpe:'7–8', rest:'2–3 min',
      note:'De pie, agarre a la anchura de hombros, barra a nivel de clavículas. Aprieta los glúteos y el core para evitar la hiperlordosis lumbar. Sube la barra en vertical pasando ligeramente por delante de la cara y lleva la cabeza hacia adelante cuando la barra supere la frente. Baja con control hasta el punto de partida.' },
    { id:'ARP', name:'Arnold press',
      sets:3, reps:'10–12', rpe:'7–8', rest:'90 seg',
      note:'Empieza con las mancuernas a la altura del pecho, palmas mirando hacia ti. Al subir, rota las muñecas hacia afuera para que al llegar arriba las palmas miren al frente. Este giro activa el deltoides anterior y medio de forma conjunta. Baja revirtiendo la rotación de forma lenta y controlada.' },
    { id:'EL',  name:'Elevaciones laterales con mancuerna',
      sets:4, reps:'15–20', rpe:'7', rest:'60 seg',
      note:'Ligera inclinación del torso hacia adelante para alinear mejor el deltoides medio con el movimiento. Sube los brazos hasta la horizontal con los codos ligeramente por encima de las muñecas, como si estuvieras vertiendo agua de una jarra. Baja de forma muy lenta (3-4 seg); la fase excéntrica es donde más se estimula el deltoides.' },
    { id:'EP',  name:'Elevaciones laterales en polea baja',
      sets:3, reps:'15–20', rpe:'8', rest:'60 seg',
      note:'La polea mantiene tensión constante desde el inicio del movimiento, a diferencia de las mancuernas que tienen poca resistencia abajo. Toma el cable con la mano cruzada (cable pasa por delante del cuerpo). Sube el brazo hasta la horizontal sin girar el torso; la tensión continua durante todo el rango es la ventaja clave.' },
    { id:'EF',  name:'Elevaciones frontales con mancuerna',
      sets:3, reps:'12–15', rpe:'7', rest:'60 seg',
      note:'De pie con las mancuernas delante de los muslos, sube un brazo (o los dos) hasta la horizontal con el pulgar ligeramente arriba. No sobrepasar la altura de los hombros. El deltoides anterior ya recibe mucho trabajo indirecto en press; no lo sobrecarges: mantén pesos moderados y rango limpio.' },
    { id:'FP',  name:'Facepull en polea alta',
      sets:3, reps:'15–20', rpe:'6–7', rest:'60 seg',
      note:'Con la cuerda a la altura de la cara, tira hacia la frente abriendo los codos hacia arriba y afuera. Las manos deben llegar a los lados de las orejas al final del movimiento, no hacia el cuello. Este ejercicio fortalece los rotadores externos del hombro y los trapecios medios, esencial para la salud de la articulación.' },
    { id:'RC',  name:'Remo al cuello con barra/polea',
      sets:3, reps:'12–15', rpe:'7', rest:'60 seg',
      note:'Usa agarre ancho (más allá de los hombros) para reducir el estrés en la articulación del hombro. Tira de la barra hacia el mentón con los codos subiendo hacia afuera y arriba. No la subas más allá del mentón. Con agarre estrecho el riesgo de pinzamiento aumenta mucho, así que mantén siempre el agarre ancho.' },
  ],
  'Bíceps': [
    { id:'CBA', name:'Curl con barra',
      sets:3, reps:'8–12', rpe:'7–8', rest:'90 seg',
      note:'De pie con la barra a la anchura de hombros y los codos pegados al cuerpo. Sube la barra rotando la muñeca hacia afuera (supinación) al llegar arriba para conseguir la contracción máxima del bíceps. Baja de forma controlada en 3 seg sin dejar caer el peso; el excéntrico lento es fundamental para el desarrollo muscular.' },
    { id:'CM',  name:'Curl martillo con mancuernas',
      sets:3, reps:'10–14', rpe:'8', rest:'90 seg',
      note:'Agarre neutro durante todo el movimiento. Este curl trabaja el braquial y el braquiorradial además del bíceps, dando más grosor al brazo. Mantén los codos fijos a los lados del torso y sube de forma alterna o bilateral. Evita balancear el torso; si lo haces, el peso es excesivo.' },
    { id:'CB',  name:'Curl en polea baja',
      sets:3, reps:'12–15', rpe:'8', rest:'60 seg',
      note:'La polea proporciona tensión constante durante todo el rango, especialmente en el estiramiento (posición baja) donde las mancuernas no tienen resistencia. Adelanta ligeramente los codos respecto al torso para maximizar la tensión en la parte alta. Baja hasta extensión completa en cada repetición.' },
    { id:'CI',  name:'Curl inclinado con mancuernas',
      sets:3, reps:'10–12', rpe:'8', rest:'90 seg',
      note:'Siéntate en banco inclinado a 45-60°. Al colgar los brazos, el bíceps queda en máximo estiramiento desde el inicio, lo que aumenta el reclutamiento muscular. Sube sin mover los codos hacia adelante; si los codos avanzan, pierdes el beneficio del estiramiento. Movimiento lento y controlado.' },
    { id:'CPR', name:'Curl en predicador (Scott)',
      sets:3, reps:'10–12', rpe:'8', rest:'90 seg',
      note:'El apoyo del brazo sobre el pad elimina el impulso y aísla completamente el bíceps. Baja hasta casi la extensión completa —no bloquees el codo— y sube apretando el bíceps arriba. El punto de mayor dificultad es la parte baja del movimiento; controla especialmente esa fase.' },
    { id:'CC',  name:'Curl concentrado',
      sets:3, reps:'12–15', rpe:'8', rest:'60 seg',
      note:'Sentado, apoya el codo en la cara interna del muslo. Sube la mancuerna girando la muñeca hacia afuera al final para supinar y alcanzar la máxima contracción. La posición del brazo fuerza la activación del bíceps en el plano correcto. Baja hasta extensión completa y repite sin balanceo.' },
    { id:'CINV', name:'Curl invertido (agarre prono)',
      sets:3, reps:'12–15', rpe:'8.5–9', rest:'60–90 seg',
      note:'Ejecución: Agarre fuerte, codos pegados al cuerpo y sube controlando la bajada. Si la barra recta en pronación te molesta en una muñeca, usa la cuerda para un agarre intermedio entre neutro y pronado. Busca un bombeo masivo con repeticiones altas y control en el excéntrico.' },
  ],
  'Tríceps': [
    { id:'ET',  name:'Extensión de tríceps en polea',
      sets:3, reps:'12–15', rpe:'7–8', rest:'60 seg',
      note:'De pie frente a la polea alta, codos pegados al cuerpo a los lados del torso durante todo el ejercicio. Empuja hacia abajo hasta la extensión completa y vuelve lentamente hasta que los antebrazos queden paralelos al suelo como mínimo. Si los codos se abren al subir, el peso es excesivo. La cuerda permite rotar las muñecas hacia afuera al final para mayor contracción.' },
    { id:'EC',  name:'Extensión sobre cabeza con mancuerna',
      sets:3, reps:'10–12', rpe:'8', rest:'90 seg',
      note:'Sentado o de pie, lleva la mancuerna detrás de la cabeza con ambas manos (bilateral) o una sola. Los codos apuntan al techo y no se abren hacia los lados. Baja la mancuerna detrás de la cabeza hasta sentir el estiramiento en el tríceps largo y sube hasta la extensión casi completa. El estiramiento en esta posición maximiza la activación del tríceps largo.' },
    { id:'PRF', name:'Press francés con barra EZ',
      sets:3, reps:'10–12', rpe:'7–8', rest:'90 seg',
      note:'Tumbado, sujeta la barra EZ con agarre cerrado y los brazos verticales. Baja la barra hacia la frente o detrás de la cabeza doblando solo los codos; los brazos no se mueven. Sube a la posición inicial. La barra EZ reduce la tensión en las muñecas respecto a la barra recta. Empieza con peso moderado hasta dominar la técnica.' },
    { id:'FT',  name:'Fondos en paralelas (tríceps)',
      sets:3, reps:'8–12', rpe:'7–8', rest:'90 seg',
      note:'Mantén el torso completamente vertical para que la carga vaya al tríceps y no al pecho. Los codos se doblan hacia atrás, no hacia afuera. Baja hasta que los codos formen 90° y sube a extensión casi completa. Si añades peso con cinturón, asegúrate de que la técnica no se deteriora.' },
    { id:'KB',  name:'Kickback con mancuerna',
      sets:3, reps:'12–15', rpe:'7', rest:'60 seg',
      note:'Apoyado en banco, lleva el codo a la altura del torso o ligeramente por encima. Extiende el antebrazo hasta alinearlo con el torso y aguanta 1 seg en contracción máxima. Baja controlado. El error más común es no subir el codo lo suficiente; si el codo está bajo el torso, el tríceps no llega a la contracción completa.' },
    { id:'EOC', name:'Tríceps tras nuca en polea alta',
      sets:3, reps:'12–15', rpe:'7–8', rest:'60 seg',
      note:'De espaldas a la polea alta, agarra la cuerda por encima de la cabeza con los codos apuntando al techo. Extiende los antebrazos hacia arriba/adelante hasta la extensión completa manteniendo los codos fijos — si se abren, el peso es excesivo. Vuelve lentamente hasta sentir el estiramiento del tríceps largo. La posición overhead es la que más activa la cabeza larga del tríceps, que es la porción más grande del músculo.' },
  ],
  'Core': [
    { id:'PF',  name:'Plancha frontal',
      sets:3, reps:'30–45 seg', rpe:'7', rest:'60 seg',
      note:'Apoyado en antebrazos y puntas de los pies, crea una línea recta de cabeza a talones. Aprieta glúteos, cuádriceps y core de forma activa —no es simplemente aguantar, sino contraer. La zona lumbar no debe hundirse ni elevarse. Si no puedes mantener la posición con calidad, reduce el tiempo en lugar de aguantar con mala forma.' },
    { id:'PL',  name:'Plancha lateral',
      sets:3, reps:'20–30 seg por lado', rpe:'7', rest:'60 seg',
      note:'Apoyado en el antebrazo y el lateral del pie, la cadera debe estar elevada formando una línea recta lateral. Aprieta el oblicuo para evitar que la cadera caiga. La variante con rodilla apoyada es válida para empezar. Para progresar, añade abducción de la pierna de arriba.' },
    { id:'CP',  name:'Crunch en polea alta',
      sets:3, reps:'12–15', rpe:'7', rest:'60 seg',
      note:'Arrodíllado frente a la polea alta con la cuerda detrás de la cabeza. Flexiona la columna llevando los codos hacia las rodillas —no es un tirón de brazos, es una flexión del raquis. Mantén la tensión en el abdomen durante todo el movimiento y evita usar el impulso de los brazos.' },
    { id:'DB',  name:'Dead bug',
      sets:3, reps:'8–10 por lado', rpe:'6', rest:'60 seg',
      note:'Tumbado boca arriba con brazos al techo y caderas y rodillas a 90°. Extiende simultáneamente el brazo derecho sobre la cabeza y la pierna izquierda hacia el suelo, manteniendo la zona lumbar pegada al suelo en todo momento. Ese contacto lumbar es la clave: si se levanta, reduce el rango de movimiento.' },
    { id:'RA',  name:'Rueda abdominal',
      sets:3, reps:'8–12', rpe:'8', rest:'90 seg',
      note:'De rodillas, rueda hacia adelante manteniendo el core muy apretado para que la lumbar no se hunda. Llega hasta el punto en que puedas volver con control —no extiendas más de lo que puedes controlar al volver. La fase de vuelta (concéntrica) es la más exigente: tira del abdomen hacia arriba y atrás para regresar.' },
    { id:'ELP', name:'Elevación de piernas en barra',
      sets:3, reps:'10–15', rpe:'7–8', rest:'60 seg',
      note:'Colgado de la barra, sube las piernas extendidas o con rodillas dobladas hasta la horizontal o más arriba. Evita el balanceo usando el core para controlar el movimiento. Baja de forma lenta (3 seg) para que el recto abdominal trabaje también en excéntrico. Si balanceas, es señal de que el peso es excesivo o el core está desactivado.' },
    { id:'CR',  name:'Crunch en suelo',
      sets:3, reps:'15–20', rpe:'6–7', rest:'60 seg',
      note:'Tumbado con las rodillas dobladas, coloca los dedos detrás de las orejas sin tirar del cuello. Flexiona la columna despegando solo los hombros del suelo —el movimiento es pequeño pero intenso si se hace con contracción consciente. Exhala al subir y aprieta el abdomen en la posición alta.' },
    { id:'OP',  name:'Oblicuos en polea',
      sets:3, reps:'12–15 por lado', rpe:'7', rest:'60 seg',
      note:'De pie lateral a la polea, agarra el mango por encima de la cabeza. Tira hacia abajo lateralmente usando el oblicuo del mismo lado, no los brazos. Mantén las caderas estables —solo el torso se mueve. Trabaja un lado completamente antes de cambiar, con movimiento lento y controlado.' },
  ],
  'Cardio': [
    { id:'REMO',  name:'Remo (máquina)',          type:'cardio', duration_min:15, distance_m:3000, level:5, note:'Mantén la espalda recta, empuja con las piernas primero y luego tira con los brazos. Cadencia constante, no uses solo los brazos. Ideal para calentamiento o HIIT.' },
    { id:'CINTA', name:'Cinta de correr',          type:'cardio', duration_min:20, distance_m:3000, level:6, note:'Empieza con inclinación del 1–2% para simular terreno real. Mantén la postura erguida y los brazos relajados. Alterna entre trote suave y series de mayor intensidad según el objetivo.' },
    { id:'BICI',  name:'Bicicleta estática',       type:'cardio', duration_min:20, distance_m:8000, level:5, note:'Ajusta el sillín de modo que la rodilla quede ligeramente doblada en el punto más bajo del pedaleo. Mantén el core activado y no te apoyes excesivamente en el manillar.' },
    { id:'ELIP',  name:'Elíptica',                 type:'cardio', duration_min:20, distance_m:4000, level:5, note:'Movimiento fluido sin impacto en las articulaciones. Mantén el talón apoyado en el pedal y usa los brazos de forma activa para aumentar el gasto calórico. Ideal para recuperación activa.' },
    { id:'SKIG',  name:'SkiErg',                   type:'cardio', duration_min:10, distance_m:2000, level:6, note:'Movimiento simétrico de remo aéreo: tira con ambos brazos desde arriba hacia abajo mientras flexionas ligeramente las rodillas. Enganche entre core, hombros y piernas. Muy exigente, empieza con intervalos cortos.' },
    { id:'ESCAL', name:'Escaladora (StairMaster)',  type:'cardio', duration_min:15, distance_m:0,    level:5, note:'No te apoyes en los laterales con los brazos; el esfuerzo lo hacen las piernas y el glúteo. Paso completo hasta abajo para activar el glúteo mayor. Una de las máquinas con mayor gasto calórico por minuto.' },
  ],
};

// Flat map para búsqueda por id
const CATALOG_BY_ID = {};
Object.values(EXERCISE_CATALOG).forEach(group => {
  group.forEach(ex => { CATALOG_BY_ID[ex.id] = ex; });
});
